### ISSUE TITLE
UTC offsets not handled

### ISSUE THREAD

**Issue by dzchilds** [Moohan/octopusR#19]
The `get_consumption` function returns NA when a date-time string returned by the API contains a UTC offset to account for daylight savings time, i.e. this fails when there are date-time strings such as `"2023-04-03T00:30:00+01:00"`:

```r
iso_8601_format <- "%Y-%m-%dT%H:%M:%SZ"
consumption_data$interval_start <- strptime(
    consumption_data$interval_start,
    iso_8601_format
)
```

I think the `lubridate::ymd_hms` uses a flexible parser that will handle the offset.

**Comment by Moohan** [comment]
Thanks for pointing that out. I had issues trying to test that as I only had access to data that wasn't offset.

I can look at using lubridate as you suggest, but also happy for you to do a PR if you're interested?

I'm away this week, so it will be at least that long before I could look at it 😅

**Comment by dzchilds** [comment]
Just back from a break myself. I'll be away from my desk next week but could look at a PR when I get back if I can carve out some time. That said, I was thinking about this a bit more, and I wonder if the 'right' fix would be to return the date-times as a string (i.e. leave them as returned by the API). There is quite a wide range of different tools for handling dates in R, so maybe it would be simplest to let users decide how they want to deal with them. Just a thought. Your call, obvs!

**Comment by Moohan** [comment]
Just had a quick look at this and the problem is exactly as you described. `lubridate::ymd_hms` seems to parse it fine and we could even pass through the `tz` parameter to allow specifying a timezone other than `"UTC"`.

My current best thought is to have a `tz` param in the `get_consumption` function with a default of `"UTC"`. Include `lubridate` as a suggested package, then if the user doesn't have it installed, `octopusR` could give a message and return the dates as characters. Alternatively, the user could specify `tz = NULL` to explicitly not use lubricate for parsing.

Hopefully, that sounds like a good solution to you but let me know your thoughts or different ideas? I'll not code that up just yet but happy to do it (probably this / next week)!

**Comment by Moohan** [comment]
@dzchilds - Sorry for the massive delay! I wrote up the solution on #22 ages ago and for no particular reason never got round to checking and pushing it. I think this should resolve your issue in the way we discussed.

**Comment by dzchilds** [comment]
Thanks, James. I checked at the weekend, and all is working as advertised.
Thanks for the fix. Much appreciated.

--
Professor Dylan Z. Childs
Ecology and Evolutionary Biology
School of Biosciences
University of Sheffield, Sheffield, S10 2TN, UK
📞  (+44) (0)114 222 4313
🗓️  view availability
***@***.***&ctz=Europe/London&mode=WEEK>
